[package]
name = "clear_on_drop"
version = "0.1.0"
authors = ["Cesar Eduardo Barros <cesarb@cesarb.eti.br>"]
description = "Helpers for clearing sensitive data on the stack and heap"
repository = "https://github.com/cesarb/clear_on_drop"
documentation = "https://cesarb.github.io/clear_on_drop/clear_on_drop/"
readme = "README.md"
keywords = ["clear_on_drop", "clear_stack", "zeroize"]
license = "MIT OR Apache-2.0"

build = "build.rs"

[features]
no_cc = []
nightly = ["no_cc"]

[build-dependencies]
gcc = "0.3"

[dependencies]
