[package]
name = "clear_on_drop"
version = "0.1.0"
authors = ["Cesar Eduardo Barros <cesarb@cesarb.eti.br>"]

build = "build.rs"

[features]
no_cc = []
nightly = ["no_cc"]

[build-dependencies]
gcc = "0.3"

[dependencies]
